### ISSUE TITLE
Delete todos

### ISSUE THREAD

**Issue by dig77** [Lalit2005/paperclip#1]
Hi, is it possible to delete todos?

**Comment by Lalit2005** [comment]
You mean delete todos that have not been completed? that's possible

I haven't implemented deleting done todos yet..
But it's definitely in the roadmap which I'll make public soon 😃

**Comment by dig77** [comment]
I mean deleting the todos list. I´ve created two todos list and i want to delete one of them.

**Comment by Lalit2005** [comment]
Oops, had a lot to do so forgot add that!!
Thanks for reminding
It'll try my best to finish it up within 24 hrs 🤞

**Comment by dig77** [comment]
No worries, just keep the good work. You´re on the right way.

**Comment by Lalit2005** [comment]
Done @dig77 !!

Now you can edit **Todolist metadata** and **move them to trash**. But I haven't implemented the trash (the [trash page](https://usepaperclip.vercel.app/app/trash)) for todolists yet. By the way, I had to take 24 hours more than what I said 😅 . But I was able to all these features :

- Notes automatically save now!! So no more `Save` button in notes
- Update todolist name and description
- Move todolists to trash

**Comment by dig77** [comment]
well done, just tested the new features.

You rock.
