### ISSUE TITLE
Empty Title Error in Playgrounds Bug

### ISSUE THREAD

**Issue by KaisTayari** [Lalit2005/paperclip#3]
When editing a playground's title to an empty string the page shows 

> Application error: a client-side exception has occurred (developer guidance). 

Everytime you try load the -playground- page. 

Note: In homepage, when you click in the empty space under "Your Playgrounds" you can redit the template and regive it a name.

**Comment by Lalit2005** [comment]
Fixed it! Thanks for opening the issue!

Btw, added validation while changing the playground name too so that empty name cannot be provided. Even if its changed via the API, the app wouldn't break!

Thanks again @KaisTayari 😄
